[book]
authors = ["Zoe Winters"]
language = "en"
multilingual = false
src = "src"
title = "Dusk Keyboard Layout"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
